# General
config_file_version: 1.1
vehicle_name: mete # only necessary while debugging through an IDE
debug: True # needs to be set True while debugging through an IDE
save_experiment_results: True # save the plots under the results folder
save_to_pickle: False
show_plots: True # display the plots if save_experiment_results is False

# AprilTag Detection Related
multitag_pose_estimation: False # not yet implemented
# single_apriltag_id: 1
single_apriltag_train_id: 1
single_apriltag_validation_id: 1
# Optimization
model: gt
cost_function_type: AsRMSE # see include/calibration/cost_function_library.py for available options

# Data preperation - see include/calibration/data_preperation_utils.py (smooth function) for more details.
filter_type: hanning
filter_length: 11
discard_first_n_data: 1
discard_last_n_data: 1
down_sample_rate: 1

# Model-Spesific Parameters
# input_dependent_kinematic_drive
interval_count: 10

# Velocity estimation from position data
spline_type: lsq_spline # lsq_spline or b_spline
spline_smoothing_factor: 10
lsq_spline_order: 3
lsq_spline_knot_every: 3
lsq_discard_n_at_boundary: 1
densification_factor: 3
discard_n_after_spline_fitting: 1

# Model assessment logic - see include/calibration/model_assessment.py for more details.
assessment_rule: nsap_threshold
nsap_threshold: 1.7

# Upload plots to plotly
upload_plots: False
