#parameters for pi_camera/camera_node
framerate_high: 30
framerate_low:  15
res_w: 640
res_h: 480
#decompress: false
#publish_info: false
shutter_mode: custom # "custom" or "default"
custom_shutter_speed: 10000 # microseconds