# General
vehicle_name: mete # only necessary while debugging through an IDE
debug: True # needs to be set True while debugging through an IDE
save_experiment_results: False # save the plots under the results
save_to_pickle: False
show_plots: True # display the plots
# Optimization
express_measurements_in: None # or cartesian. polar coordinates is the recommended option
cost_function_type: AsRMSE # see include/calibration/cost_function_library.py for available options

# Data preperation - see include/calibration/data_preperation_utils.py (smooth function) for more details.
filter_type: flat
filter_length: 17
discard_first_n_data: 10
discard_last_n_data: 5
