# General
debug: True
save_experiment_results: False
save_to_pickle: False
show_plots: True

# Optimization
express_measurements_in: polar
cost_function_type: MsRMSE

# Data preperation
filter_type: flat
filter_length: 11
discard_first_n_data: 10
discard_last_n_data: 5
